language: java

jdk:
  - oraclejdk8

sudo: false
install: true

addons:
  sonarcloud:
    organization: "yagelnasmanit-github"
    branches:
      - master
      - develop

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'