version: '2.1'
services:
  env_monitor:
    build:
       context: .
       dockerfile: Dockerfile
    volumes:
       - .:/app
    depends_on:
       - mongodb
    environment:
       - MONGO_URL=mongodb://mongodb:27017
       #-Dmongo.connect.uri=mongodb://localhost:27017
    ports:
       - "3000:8080"

  mongodb:
    image: mongo:3.4
    ports:
         - "27020:27017"